import type { Product, Category, Subcategory, Material, ProductVariant } from '@/types';
import { productImages } from '@/lib/product-images';

type Pool = 'footwear' | 'clothing' | 'smallGoods' | 'bags' | 'belts' | 'home';

function item(data: {
  id: string;
  slug: string;
  name: string;
  description: string;
  price: number;
  priceUsd?: number;
  category: Category;
  subcategory: Subcategory;
  material: Material;
  pool: Pool;
  img: number;
  variants: ProductVariant[];
  createdAt: string;
  badge?: Product['badge'];
  featured?: boolean;
  sizing?: string;
}): Product {
  const { pool, img, sizing, ...rest } = data;
  return {
    ...rest,
    images: productImages(pool, img),
    details: {
      materials: `100% genuine ${data.material.replace('-', ' ')} leather, sourced from Ethiopian tanneries.`,
      build: 'Hand-stitched and inspected in our Bishoftu workshop.',
      sizing: sizing ?? 'Contact us on WhatsApp with your measurements for a perfect fit.',
      care: 'Wipe clean and condition monthly for a lasting patina.',
      shipping: 'Addis Ababa 1–2 days · Nationwide 3–5 days · International available.',
    },
  };
}

const c = (color: string, hex: string, stock: number, size?: string) => ({
  color,
  colorHex: hex,
  stock,
  ...(size ? { size } : {}),
});

export const catalogProducts: Product[] = [
  // ─── Footwear ─────────────────────────────────────────
  item({
    id: '1',
    slug: 'heritage-oxford-shoes',
    name: 'Heritage Oxford Shoes',
    description: 'Hand-stitched full-grain oxford shoes with Goodyear welt construction.',
    price: 12500,
    priceUsd: 110,
    category: 'footwear',
    subcategory: 'mens-dress-shoes',
    material: 'full-grain',
    pool: 'footwear',
    img: 0,
    badge: 'bestseller',
    featured: true,
    variants: [c('Brown', '#8B4513', 5, '40'), c('Brown', '#8B4513', 3, '41'), c('Black', '#1A1A1A', 4, '43')],
    sizing: 'EU sizes 39–45. Runs true to size.',
    createdAt: '2025-11-01',
  }),
  item({
    id: '13',
    slug: 'derby-brogue-shoes',
    name: 'Derby Brogue Shoes',
    description: 'Perforated brogue detailing on a classic derby last for formal occasions.',
    price: 13200,
    priceUsd: 115,
    category: 'footwear',
    subcategory: 'mens-dress-shoes',
    material: 'full-grain',
    pool: 'footwear',
    img: 3,
    badge: 'bestseller',
    featured: true,
    variants: [c('Brown', '#8B4513', 4, '40'), c('Black', '#1A1A1A', 3, '42')],
    createdAt: '2026-02-01',
  }),
  item({
    id: '14',
    slug: 'monk-strap-shoes',
    name: 'Double Monk Strap Shoes',
    description: 'Sleek double monk strap shoes with solid brass buckles.',
    price: 13800,
    priceUsd: 120,
    category: 'footwear',
    subcategory: 'mens-dress-shoes',
    material: 'full-grain',
    pool: 'footwear',
    img: 4,
    badge: 'new',
    variants: [c('Black', '#1A1A1A', 3, '41'), c('Cognac', '#A0522D', 2, '43')],
    createdAt: '2026-02-10',
  }),
  item({
    id: '29',
    slug: 'womens-leather-flats',
    name: "Women's Leather Flats",
    description: 'Elegant pointed-toe flats in soft full-grain leather for all-day comfort.',
    price: 9800,
    priceUsd: 85,
    category: 'footwear',
    subcategory: 'womens-heels-flats',
    material: 'full-grain',
    pool: 'footwear',
    img: 1,
    badge: 'new',
    variants: [c('Black', '#1A1A1A', 5, '37'), c('Tan', '#C4956A', 4, '38'), c('Brown', '#8B4513', 3, '39')],
    createdAt: '2026-03-01',
  }),
  item({
    id: '30',
    slug: 'artisan-leather-sandals',
    name: 'Artisan Leather Sandals',
    description: 'Hand-cut leather sandals with cushioned footbed — perfect for Ethiopian weather.',
    price: 6500,
    priceUsd: 55,
    category: 'footwear',
    subcategory: 'sandals',
    material: 'full-grain',
    pool: 'footwear',
    img: 2,
    variants: [c('Brown', '#8B4513', 8, '40'), c('Tan', '#C4956A', 6, '42'), c('Black', '#1A1A1A', 5, '44')],
    createdAt: '2026-03-02',
  }),
  item({
    id: '10',
    slug: 'loafers-classic',
    name: 'Classic Leather Loafers',
    description: 'Penny loafers handcrafted for business casual elegance.',
    price: 11800,
    priceUsd: 105,
    category: 'footwear',
    subcategory: 'loafers',
    material: 'full-grain',
    pool: 'footwear',
    img: 2,
    variants: [c('Brown', '#8B4513', 4, '40'), c('Black', '#1A1A1A', 2, '44')],
    createdAt: '2025-11-10',
  }),
  item({
    id: '6',
    slug: 'chelsea-boots',
    name: 'Chelsea Boots',
    description: 'Sleek Chelsea boots with elastic side panels for office or evening wear.',
    price: 14200,
    priceUsd: 125,
    category: 'footwear',
    subcategory: 'boots',
    material: 'full-grain',
    pool: 'footwear',
    img: 1,
    variants: [c('Black', '#1A1A1A', 4, '41'), c('Brown', '#8B4513', 2, '43')],
    createdAt: '2025-11-20',
  }),
  item({
    id: '31',
    slug: 'handcrafted-moccasins',
    name: 'Handcrafted Moccasins',
    description: 'Traditional hand-stitched moccasin construction with supple leather upper.',
    price: 8900,
    priceUsd: 78,
    category: 'footwear',
    subcategory: 'moccasins',
    material: 'full-grain',
    pool: 'footwear',
    img: 5,
    variants: [c('Tan', '#C4956A', 5, '40'), c('Brown', '#8B4513', 4, '42')],
    createdAt: '2026-03-03',
  }),

  // ─── Bags ─────────────────────────────────────────────
  item({
    id: '25',
    slug: 'artisan-shoulder-bag',
    name: 'Artisan Shoulder Bag',
    description: 'Structured shoulder bag with adjustable strap and interior zip pocket.',
    price: 14200,
    priceUsd: 125,
    category: 'bags',
    subcategory: 'shoulder-bags',
    material: 'full-grain',
    pool: 'bags',
    img: 4,
    badge: 'new',
    variants: [c('Cognac', '#A0522D', 4), c('Black', '#1A1A1A', 3)],
    createdAt: '2026-03-04',
  }),
  item({
    id: '26',
    slug: 'classic-handbag',
    name: 'Classic Handbag',
    description: 'Timeless top-handle handbag with magnetic closure and gold-tone hardware.',
    price: 16800,
    priceUsd: 148,
    category: 'bags',
    subcategory: 'handbags-purses',
    material: 'full-grain',
    pool: 'bags',
    img: 0,
    variants: [c('Brown', '#8B4513', 3), c('Black', '#1A1A1A', 2)],
    createdAt: '2026-03-05',
  }),
  item({
    id: '19',
    slug: 'leather-tote-bag',
    name: 'Leather Tote Bag',
    description: 'Oversized open-top tote with structured base for work or market days.',
    price: 16800,
    priceUsd: 148,
    category: 'bags',
    subcategory: 'tote-bags',
    material: 'full-grain',
    pool: 'bags',
    img: 2,
    badge: 'bestseller',
    featured: true,
    variants: [c('Cognac', '#A0522D', 4), c('Black', '#1A1A1A', 3)],
    createdAt: '2026-02-08',
  }),
  item({
    id: '27',
    slug: 'crossbody-saddle-bag',
    name: 'Crossbody Saddle Bag',
    description: 'Compact crossbody with flap closure — hands-free everyday carry.',
    price: 11500,
    priceUsd: 100,
    category: 'bags',
    subcategory: 'crossbody-bags',
    material: 'top-grain',
    pool: 'bags',
    img: 1,
    variants: [c('Tan', '#C4956A', 6), c('Brown', '#8B4513', 4)],
    createdAt: '2026-03-06',
  }),
  item({
    id: '20',
    slug: 'leather-backpack',
    name: 'Leather Backpack',
    description: 'Roll-top backpack with padded laptop sleeve for urban commuters.',
    price: 19500,
    priceUsd: 170,
    category: 'bags',
    subcategory: 'backpacks',
    material: 'full-grain',
    pool: 'bags',
    img: 3,
    badge: 'new',
    variants: [c('Brown', '#8B4513', 4), c('Black', '#1A1A1A', 3)],
    createdAt: '2026-02-20',
  }),
  item({
    id: '9',
    slug: 'messenger-bag',
    name: 'Leather Messenger Bag',
    description: 'Professional messenger with 15" laptop compartment and organizer pockets.',
    price: 18500,
    priceUsd: 165,
    category: 'bags',
    subcategory: 'laptop-briefcases',
    material: 'full-grain',
    pool: 'bags',
    img: 1,
    badge: 'bestseller',
    variants: [c('Brown', '#8B4513', 5), c('Black', '#1A1A1A', 3)],
    createdAt: '2025-10-01',
  }),
  item({
    id: '4',
    slug: 'weekender-duffle-bag',
    name: 'Weekender Duffle Bag',
    description: 'Spacious handcrafted duffle with reinforced handles and shoulder strap.',
    price: 15800,
    priceUsd: 140,
    category: 'bags',
    subcategory: 'travel-duffel-bags',
    material: 'full-grain',
    pool: 'bags',
    img: 0,
    featured: true,
    variants: [c('Cognac', '#A0522D', 4), c('Black', '#1A1A1A', 3)],
    createdAt: '2025-12-01',
  }),
  item({
    id: '28',
    slug: 'evening-clutch',
    name: 'Evening Clutch',
    description: 'Slim leather clutch with wrist strap — refined for events and evenings.',
    price: 7200,
    priceUsd: 62,
    category: 'bags',
    subcategory: 'clutch-bags',
    material: 'full-grain',
    pool: 'bags',
    img: 5,
    variants: [c('Black', '#1A1A1A', 5), c('Cognac', '#A0522D', 3)],
    createdAt: '2026-03-07',
  }),

  // ─── Belts ────────────────────────────────────────────
  item({
    id: '5',
    slug: 'handcrafted-leather-belt',
    name: 'Handcrafted Leather Belt',
    description: 'Classic 3.5cm belt with solid brass buckle from a single leather piece.',
    price: 2800,
    priceUsd: 25,
    category: 'belts',
    subcategory: 'mens-formal-belts',
    material: 'full-grain',
    pool: 'belts',
    img: 0,
    badge: 'bestseller',
    variants: [c('Brown', '#8B4513', 8, '34'), c('Black', '#1A1A1A', 5, '36')],
    createdAt: '2025-09-20',
  }),
  item({
    id: '11',
    slug: 'reversible-belt',
    name: 'Reversible Leather Belt',
    description: 'Brown on one side, black on the other — two belts in one.',
    price: 3500,
    priceUsd: 30,
    category: 'belts',
    subcategory: 'mens-casual-belts',
    material: 'top-grain',
    pool: 'belts',
    img: 1,
    variants: [c('Brown/Black', '#8B4513', 7, '34'), c('Brown/Black', '#8B4513', 5, '36')],
    createdAt: '2025-12-20',
  }),
  item({
    id: '32',
    slug: 'womens-slim-belt',
    name: "Women's Slim Belt",
    description: '2.5cm slim belt with polished brass buckle for dresses and high-waist looks.',
    price: 2600,
    priceUsd: 22,
    category: 'belts',
    subcategory: 'womens-belts',
    material: 'full-grain',
    pool: 'belts',
    img: 3,
    badge: 'new',
    variants: [c('Black', '#1A1A1A', 6, '32'), c('Tan', '#C4956A', 5, '34')],
    createdAt: '2026-03-08',
  }),
  item({
    id: '21',
    slug: 'braided-leather-belt',
    name: 'Braided Leather Belt',
    description: 'Hand-braided leather belt with vintage brass buckle.',
    price: 3800,
    priceUsd: 33,
    category: 'belts',
    subcategory: 'wide-fashion-belts',
    material: 'full-grain',
    pool: 'belts',
    img: 2,
    variants: [c('Brown', '#8B4513', 5, '32'), c('Tan', '#C4956A', 3, '36')],
    createdAt: '2026-02-12',
  }),

  // ─── Small Leather Goods ──────────────────────────────
  item({
    id: '3',
    slug: 'artisan-bifold-wallet',
    name: 'Artisan Bifold Wallet',
    description: 'Slim bifold with 6 card slots and bill compartment.',
    price: 3200,
    priceUsd: 28,
    category: 'small-leather-goods',
    subcategory: 'bifold-trifold-wallets',
    material: 'full-grain',
    pool: 'smallGoods',
    img: 0,
    badge: 'new',
    featured: true,
    variants: [c('Tan', '#C4956A', 12), c('Brown', '#8B4513', 8), c('Black', '#1A1A1A', 6)],
    createdAt: '2026-01-10',
  }),
  item({
    id: '17',
    slug: 'zip-around-wallet',
    name: 'Zip-Around Wallet',
    description: 'Secure zip-around design with 12 card slots and coin pocket.',
    price: 4200,
    priceUsd: 37,
    category: 'small-leather-goods',
    subcategory: 'bifold-trifold-wallets',
    material: 'full-grain',
    pool: 'smallGoods',
    img: 3,
    variants: [c('Black', '#1A1A1A', 9), c('Brown', '#8B4513', 7)],
    createdAt: '2026-02-05',
  }),
  item({
    id: '8',
    slug: 'card-holder-wallet',
    name: 'Minimalist Card Holder',
    description: 'Ultra-slim card holder for 4–6 cards and folded bills.',
    price: 1800,
    priceUsd: 16,
    category: 'small-leather-goods',
    subcategory: 'card-holders',
    material: 'full-grain',
    pool: 'smallGoods',
    img: 1,
    variants: [c('Black', '#1A1A1A', 15), c('Tan', '#C4956A', 10)],
    createdAt: '2025-12-15',
  }),
  item({
    id: '18',
    slug: 'coin-purse-key-organizer',
    name: 'Coin Purse & Key Organizer',
    description: 'Compact coin purse with built-in key ring and card slot.',
    price: 2200,
    priceUsd: 19,
    category: 'small-leather-goods',
    subcategory: 'coin-purses',
    material: 'top-grain',
    pool: 'smallGoods',
    img: 4,
    badge: 'new',
    variants: [c('Tan', '#C4956A', 14), c('Black', '#1A1A1A', 11)],
    createdAt: '2026-02-18',
  }),
  item({
    id: '12',
    slug: 'travel-passport-wallet',
    name: 'Travel Passport Wallet',
    description: 'All-in-one organizer with passport slot, cards, and boarding pass sleeve.',
    price: 4500,
    priceUsd: 40,
    category: 'small-leather-goods',
    subcategory: 'passport-holders',
    material: 'full-grain',
    pool: 'smallGoods',
    img: 2,
    badge: 'last-one',
    featured: true,
    variants: [c('Cognac', '#A0522D', 1), c('Black', '#1A1A1A', 3)],
    createdAt: '2026-01-15',
  }),
  item({
    id: '22',
    slug: 'leather-keychain',
    name: 'Leather Keychain',
    description: 'Hand-stitched key fob with sturdy brass snap hook.',
    price: 950,
    priceUsd: 8,
    category: 'small-leather-goods',
    subcategory: 'keychains',
    material: 'full-grain',
    pool: 'smallGoods',
    img: 5,
    variants: [c('Brown', '#8B4513', 20), c('Black', '#1A1A1A', 18)],
    createdAt: '2026-02-22',
  }),

  // ─── Clothing & Accessories ───────────────────────────
  item({
    id: '2',
    slug: 'classic-leather-jacket',
    name: 'Classic Leather Jacket',
    description: 'Rugged yet refined top-grain jacket for the modern professional.',
    price: 28500,
    priceUsd: 250,
    category: 'clothing-accessories',
    subcategory: 'leather-jackets',
    material: 'top-grain',
    pool: 'clothing',
    img: 0,
    badge: 'bestseller',
    featured: true,
    variants: [c('Black', '#1A1A1A', 3, 'M'), c('Brown', '#8B4513', 4, 'XL')],
    sizing: 'Slim fit. Size up for layering.',
    createdAt: '2025-10-15',
  }),
  item({
    id: '7',
    slug: 'bomber-jacket',
    name: 'Leather Bomber Jacket',
    description: 'Modern bomber silhouette with ribbed cuffs and hem.',
    price: 32000,
    priceUsd: 280,
    category: 'clothing-accessories',
    subcategory: 'leather-jackets',
    material: 'top-grain',
    pool: 'clothing',
    img: 1,
    badge: 'new',
    variants: [c('Brown', '#8B4513', 2, 'M'), c('Brown', '#8B4513', 3, 'L')],
    createdAt: '2026-01-05',
  }),
  item({
    id: '15',
    slug: 'vintage-rider-jacket',
    name: 'Vintage Rider Jacket',
    description: 'Asymmetric zip motorcycle jacket with quilted shoulders.',
    price: 34500,
    priceUsd: 300,
    category: 'clothing-accessories',
    subcategory: 'leather-jackets',
    material: 'full-grain',
    pool: 'clothing',
    img: 2,
    badge: 'bestseller',
    featured: true,
    variants: [c('Black', '#1A1A1A', 2, 'M'), c('Black', '#1A1A1A', 3, 'L')],
    createdAt: '2026-01-28',
  }),
  item({
    id: '16',
    slug: 'suede-trucker-jacket',
    name: 'Suede Trucker Jacket',
    description: 'Western-inspired trucker jacket in buttery suede with snap buttons.',
    price: 26500,
    priceUsd: 230,
    category: 'clothing-accessories',
    subcategory: 'leather-jackets',
    material: 'suede',
    pool: 'clothing',
    img: 3,
    badge: 'new',
    variants: [c('Tan', '#C4956A', 2, 'S'), c('Brown', '#8B4513', 2, 'L')],
    createdAt: '2026-02-15',
  }),
  item({
    id: '33',
    slug: 'heritage-leather-vest',
    name: 'Heritage Leather Vest',
    description: 'Sleeveless full-grain vest with zip front and welt pockets.',
    price: 18500,
    priceUsd: 160,
    category: 'clothing-accessories',
    subcategory: 'leather-vests',
    material: 'full-grain',
    pool: 'clothing',
    img: 4,
    variants: [c('Brown', '#8B4513', 3, 'M'), c('Black', '#1A1A1A', 2, 'L')],
    createdAt: '2026-03-09',
  }),
  item({
    id: '34',
    slug: 'leather-cap',
    name: 'Leather Baseball Cap',
    description: 'Structured leather cap with adjustable brass buckle strap.',
    price: 4200,
    priceUsd: 36,
    category: 'clothing-accessories',
    subcategory: 'caps-hats',
    material: 'top-grain',
    pool: 'clothing',
    img: 0,
    variants: [c('Black', '#1A1A1A', 8), c('Brown', '#8B4513', 6)],
    createdAt: '2026-03-10',
  }),
  item({
    id: '24',
    slug: 'artisan-leather-gloves',
    name: 'Artisan Leather Gloves',
    description: 'Unlined driving gloves with touchscreen-compatible fingertips.',
    price: 5200,
    priceUsd: 45,
    category: 'clothing-accessories',
    subcategory: 'gloves',
    material: 'nubuck',
    pool: 'clothing',
    img: 1,
    badge: 'last-one',
    featured: true,
    variants: [c('Brown', '#8B4513', 1, 'M'), c('Black', '#1A1A1A', 3, 'L')],
    createdAt: '2026-02-25',
  }),
  item({
    id: '23',
    slug: 'handcrafted-watch-strap',
    name: 'Handcrafted Watch Strap',
    description: 'Replacement leather strap with quick-release pins. 20mm and 22mm.',
    price: 2800,
    priceUsd: 25,
    category: 'clothing-accessories',
    subcategory: 'watch-straps',
    material: 'full-grain',
    pool: 'clothing',
    img: 2,
    badge: 'bestseller',
    variants: [c('Brown', '#8B4513', 8, '22mm'), c('Black', '#1A1A1A', 7, '22mm')],
    createdAt: '2026-02-14',
  }),

  // ─── Home & Office ────────────────────────────────────
  item({
    id: '35',
    slug: 'leather-journal-cover',
    name: 'Leather Journal Cover',
    description: 'Refillable A5 journal cover with pen loop and card pocket.',
    price: 3800,
    priceUsd: 32,
    category: 'home-office',
    subcategory: 'notebook-covers',
    material: 'full-grain',
    pool: 'home',
    img: 0,
    variants: [c('Brown', '#8B4513', 10), c('Black', '#1A1A1A', 8)],
    createdAt: '2026-03-11',
  }),
  item({
    id: '36',
    slug: 'desk-organizer-tray',
    name: 'Leather Desk Organizer',
    description: 'Desktop tray for pens, cards, and phone — keeps your workspace refined.',
    price: 4500,
    priceUsd: 38,
    category: 'home-office',
    subcategory: 'desk-accessories',
    material: 'top-grain',
    pool: 'home',
    img: 1,
    variants: [c('Cognac', '#A0522D', 6), c('Black', '#1A1A1A', 5)],
    createdAt: '2026-03-12',
  }),
  item({
    id: '37',
    slug: 'leather-coasters-set',
    name: 'Leather Coasters (Set of 4)',
    description: 'Hand-cut round coasters with Brana deboss — protects surfaces in style.',
    price: 2400,
    priceUsd: 20,
    category: 'home-office',
    subcategory: 'coasters',
    material: 'full-grain',
    pool: 'home',
    img: 2,
    variants: [c('Brown', '#8B4513', 12), c('Tan', '#C4956A', 10)],
    createdAt: '2026-03-13',
  }),
  item({
    id: '38',
    slug: 'leather-photo-frame',
    name: 'Leather Photo Frame',
    description: '4×6 leather-wrapped photo frame with stand — a thoughtful gift piece.',
    price: 3200,
    priceUsd: 28,
    category: 'home-office',
    subcategory: 'photo-frames',
    material: 'full-grain',
    pool: 'home',
    img: 3,
    variants: [c('Cognac', '#A0522D', 7), c('Brown', '#8B4513', 5)],
    createdAt: '2026-03-14',
  }),
  item({
    id: '39',
    slug: 'leather-cushion-cover',
    name: 'Leather Cushion Cover',
    description: 'Decorative leather cushion cover with hidden zip — adds warmth to any room.',
    price: 5800,
    priceUsd: 50,
    category: 'home-office',
    subcategory: 'cushion-covers',
    material: 'top-grain',
    pool: 'home',
    img: 4,
    variants: [c('Brown', '#8B4513', 4), c('Black', '#1A1A1A', 3)],
    createdAt: '2026-03-15',
  }),

  // ─── Gift Items ───────────────────────────────────────
  item({
    id: '40',
    slug: 'engraved-gift-wallet',
    name: 'Custom Engraved Wallet',
    description: 'Bifold wallet with personalized initials embossed — made to order in 3–5 days.',
    price: 4800,
    priceUsd: 42,
    category: 'gifts',
    subcategory: 'engraved-wallets',
    material: 'full-grain',
    pool: 'smallGoods',
    img: 1,
    badge: 'new',
    featured: true,
    variants: [c('Brown', '#8B4513', 20), c('Black', '#1A1A1A', 15)],
    createdAt: '2026-03-16',
  }),
  item({
    id: '41',
    slug: 'executive-gift-set',
    name: 'Executive Gift Set',
    description: 'Curated set: bifold wallet, formal belt, and keychain in gift box.',
    price: 8900,
    priceUsd: 78,
    category: 'gifts',
    subcategory: 'gift-sets',
    material: 'full-grain',
    pool: 'smallGoods',
    img: 0,
    badge: 'bestseller',
    featured: true,
    variants: [c('Brown', '#8B4513', 10), c('Black', '#1A1A1A', 8)],
    createdAt: '2026-03-17',
  }),
  item({
    id: '42',
    slug: 'personalized-tote-gift',
    name: 'Personalized Tote Bag',
    description: 'Leather tote with custom name embossing — ideal for weddings and corporate gifts.',
    price: 19800,
    priceUsd: 175,
    category: 'gifts',
    subcategory: 'personalized-bags',
    material: 'full-grain',
    pool: 'bags',
    img: 4,
    variants: [c('Cognac', '#A0522D', 6), c('Tan', '#C4956A', 4)],
    createdAt: '2026-03-18',
  }),
];
